We have next logging message:2023-09-02 01:20:56,802:ERROR - Exception
Traceback (most recent call last):
  File "D:\IT_Step tasks\Python\it_step_Less_8\main.py", line 8, in <module>
    print(10/0)
          ~~^~
ZeroDivisionError: division by zero
